apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: default
data:
  http_proxy: {{ .Values.proxyConfig.http_proxy }}
  HTTP_PROXY: {{ .Values.proxyConfig.http_proxy }}
  https_proxy: {{ .Values.proxyConfig.https_proxy }}
  HTTPS_PROXY: {{ .Values.proxyConfig.https_proxy }}
  no_proxy: {{ .Values.proxyConfig.no_proxy }}
  NO_PROXY: {{ .Values.proxyConfig.no_proxy }}